bucket_name: "your-bucket-name"
sample_size: 10
uploaded_images_file: "uploaded_images.json"
region: "us-east-2"  # Update this to your bucket's region
roboflow:
  api_key: "YOUR_API_KEY"
  project_name: "YOUR_PROJECT_NAME"